#!/usr/bin/env bash
# Install Aerospike C client headers/libs under .deps/ (no sudo required).
#
# Usage (from repo root):
#   ./scripts/build_libaerospike.sh
#   source .deps/aerospike-client-c.env
#   LMCACHE_AEROSPIKE_FORCE_NATIVE=1 pip install -e . --no-build-isolation
#
# By default downloads the official Ubuntu 22.04 libuv client package and
# extracts the .deb payloads into .deps/aerospike-install/. Set
# AEROSPIKE_CLIENT_C_BUILD=1 to compile from source instead (needs libyaml-dev).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPS="${ROOT}/.deps"
INSTALL="${DEPS}/aerospike-install"
ENV_FILE="${DEPS}/aerospike-client-c.env"
VERSION="${AEROSPIKE_CLIENT_C_VERSION:-7.3.0}"
UBUNTU_SERIES="${AEROSPIKE_CLIENT_C_UBUNTU:-ubuntu22.04}"
ARCH="${AEROSPIKE_CLIENT_C_ARCH:-x86_64}"

fetch_libyaml_devel() {
  local yaml_install="${DEPS}/libyaml-install"
  if [[ -f "${yaml_install}/usr/lib/x86_64-linux-gnu/libyaml.so" ]]; then
    return 0
  fi
  if ! command -v apt >/dev/null; then
    echo "libyaml.so not found; install libyaml-dev or run on Debian/Ubuntu with apt" >&2
    exit 1
  fi
  echo "==> Fetching libyaml-dev (apt download, no sudo)"
  (cd "${DEPS}" && apt download libyaml-dev libyaml-0-2 && \
    rm -rf libyaml-install && mkdir -p libyaml-install && \
    dpkg-deb -x libyaml-dev_*.deb libyaml-install && \
    dpkg-deb -x libyaml-0-2_*.deb libyaml-install)
}

write_env() {
  fetch_libyaml_devel
  local include_dir="${INSTALL}/usr/include"
  local lib_dir="${INSTALL}/usr/lib"
  cat >"${ENV_FILE}" <<EOF
# Generated by scripts/build_libaerospike.sh
export AEROSPIKE_INCLUDE_DIR=${include_dir}
export AEROSPIKE_LIBRARY_DIR=${lib_dir}
export AEROSPIKE_STATIC=0
export LD_LIBRARY_PATH=\${LD_LIBRARY_PATH:-}:${lib_dir}:/usr/local/lib
EOF
  echo "Aerospike C client ready under ${INSTALL}"
  echo "  source ${ENV_FILE}"
}

download_prebuilt() {
  mkdir -p "${DEPS}"
  local base="aerospike-client-c-libuv_${VERSION}_${UBUNTU_SERIES}_${ARCH}"
  local url="https://download.aerospike.com/artifacts/aerospike-client-c/${VERSION}/${base}.tgz"
  local tgz="${DEPS}/${base}.tgz"
  local unpack="${DEPS}/${base}"

  if [[ ! -f "${INSTALL}/usr/include/aerospike/aerospike.h" ]]; then
    echo "==> Downloading ${url}"
    curl -fsSL -o "${tgz}" "${url}"
    rm -rf "${unpack}"
    tar xzf "${tgz}" -C "${DEPS}"
    rm -rf "${INSTALL}"
    mkdir -p "${INSTALL}"
    dpkg-deb -x "${unpack}/aerospike-client-c-libuv-devel_${VERSION}-${UBUNTU_SERIES}_amd64.deb" \
      "${INSTALL}"
    dpkg-deb -x "${unpack}/aerospike-client-c-libuv_${VERSION}-${UBUNTU_SERIES}_amd64.deb" \
      "${INSTALL}"
  fi
  write_env
}

build_from_source() {
  local SRC="${DEPS}/aerospike-client-c"
  local TAG="${AEROSPIKE_CLIENT_C_REF:-v${VERSION}}"
  local EVENT_LIB="${AEROSPIKE_EVENT_LIB:-libuv}"

  missing=()
  for pkg in autoconf automake libtool libssl-dev libyaml-dev zlib1g-dev libuv1-dev; do
    dpkg -s "$pkg" >/dev/null 2>&1 || missing+=("$pkg")
  done
  if ((${#missing[@]} > 0)); then
    echo "Missing packages for source build: ${missing[*]}" >&2
    echo "Install with: sudo apt-get install -y libyaml-dev ..." >&2
    exit 1
  fi

  mkdir -p "${DEPS}"
  if [[ ! -d "${SRC}/.git" ]]; then
    git clone --depth 1 --branch "${TAG}" \
      https://github.com/aerospike/aerospike-client-c.git "${SRC}"
  fi
  cd "${SRC}"
  git submodule update --init --recursive
  make clean >/dev/null 2>&1 || true
  make -j"$(nproc)" "EVENT_LIB=${EVENT_LIB}"

  local target_dir
  target_dir="$(find target -maxdepth 1 -type d -name 'Linux*' | head -1)"
  cat >"${ENV_FILE}" <<EOF
# Generated by scripts/build_libaerospike.sh (source build)
export AEROSPIKE_INCLUDE_DIR=${SRC}/${target_dir}/include
export AEROSPIKE_LIBRARY_DIR=${SRC}/${target_dir}/lib
export AEROSPIKE_STATIC=0
export AEROSPIKE_EVENT_LIB=${EVENT_LIB}
export LD_LIBRARY_PATH=\${LD_LIBRARY_PATH:-}:/usr/local/lib
EOF
  echo "Built from source; source ${ENV_FILE}"
}

if [[ "${AEROSPIKE_CLIENT_C_BUILD:-0}" == "1" ]]; then
  build_from_source
else
  download_prebuilt
fi
